# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App – Dentist-bot-Appservice

on:
  push:
    branches: [ master ]          # cámbialo a main si tu rama es main
  workflow_dispatch:

env:
  WORKING_DIR: starter/ContosoDentistryChatBot
  NODE_VERSION: '18'              # la misma que tiene tu App Service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read              # necesario para actions/checkout

    steps:
      # 1️⃣ Clona el repo
      - uses: actions/checkout@v4

      # 2️⃣ Configura Node + cache
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: starter/ContosoDentistryScheduler/package-lock.json

      # 3️⃣ Instala dependencias y (opcional) build
      - name: npm install & build
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          npm ci
          npm run build --if-present

      # 4️⃣ Empaqueta los artefactos
      - name: Zip artifact for deployment
        working-directory: ${{ env.WORKING_DIR }}
        run: zip -r ${{ github.workspace }}/release.zip .

      # 5️⃣ Sube artefacto
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Descarga artefacto
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # 2️⃣ Descomprime
      - name: Unzip artifact
        run: unzip release.zip -d deploy_dir

      # 3️⃣ Login a Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZUREAPPSERVICE_CLIENTID_DED29219C9CE4A5188F83B1AF12FAB78 }}
          tenant-id:      ${{ secrets.AZUREAPPSERVICE_TENANTID_8AC9B901679A4A0A861FBEAAFBB89408 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_33F6158C6CEA4B5992CF540034F2F55E }}

      # 4️⃣ Despliega
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Dentist-bot-Appservice
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy_dir

