# ============================================================
# GitHub Actions – Deploy Dentist Scheduler API to Azure Web App
# ============================================================
# Requisitos previos:
#   1. En el Web App, descarga el Publish Profile (.PublishSettings)
#   2. En GitHub → Settings → Secrets → Actions
#        crea  AZUREAPPSERVICE_PUBLISHPROFILE  y pega allí el XML
#   3. Ajusta "branch: master" si tu rama principal es "main"
# ============================================================

name: Deploy Dentist Scheduler API

on:
  push:
    branches: [ master ]        # cámbialo a main si es necesario
  workflow_dispatch:

env:
  WORKING_DIR: ContosoDentistryScheduler   # subcarpeta con package.json
  ZIP_NAME: release.zip
  APP_NAME: dentist-scheduler-api          # nombre exacto del Web App

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: npm ci

      - name: Build (if present)
        working-directory: ${{ env.WORKING_DIR }}
        run: npm run build --if-present

      - name: Create deployment ZIP
        working-directory: ${{ env.WORKING_DIR }}
        run: zip -r ../${{ env.ZIP_NAME }} ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scheduler-api
          path: ${{ env.ZIP_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: scheduler-api

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          package: ${{ env.ZIP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
