name: Deploy Dentist Scheduler API

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  WORKING_DIR: starter/ContosoDentistryScheduler
  ZIP_NAME: release.zip
  APP_NAME: dentist-scheduler-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: npm ci

      - name: Build (if present)
        working-directory: ${{ env.WORKING_DIR }}
        run: npm run build --if-present

      - name: Create deployment ZIP
        run: zip -r ${{ env.ZIP_NAME }} ${{ env.WORKING_DIR }}/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scheduler-api
          path: ${{ env.ZIP_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: scheduler-api

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: Production
          package: ${{ env.ZIP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
